# Numpy Basics

In [1]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [2]:
import numpy as np

In [3]:
myOneDDarray = np.array(my_list
            )

In [4]:
myOneDDarray

array([1, 2, 3, 4, 5, 6])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## arange() and linspace functions in numpy.

In [6]:
np.linspace(0,10, 6) # Linspace divides line in given equal parts.

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [7]:
np.arange(0, 20, 2) # arange skips the given digits.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.random.randn(5,5)

array([[-1.34870051, -1.74371509,  0.67861258,  0.13935814,  0.95930445],
       [-0.47747787,  0.4134945 ,  0.37886642, -0.59595021, -0.81368035],
       [-0.8576881 , -0.0037405 ,  0.53009959,  0.18472814, -1.67503226],
       [-1.19395483,  1.43768319,  0.40803102, -0.66417507, -0.15311072],
       [ 0.20556814,  0.12474407, -0.4400232 , -0.40159552,  1.2850905 ]])

## Reshaping an array.

In [9]:
my_list = np.arange(0,20)
my_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
my_list.reshape(-4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 2D Arrays

In [13]:
my_2d_arraay = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
my_2d_arraay

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Grab 8 from 2,1
my_2d_arraay[2][1]

8