# Numpy Basics

In [1]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [2]:
import numpy as np

In [3]:
myOneDDarray = np.array(my_list
            )

In [4]:
myOneDDarray

array([1, 2, 3, 4, 5, 6])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## arange() and linspace functions in numpy.

In [6]:
np.linspace(0,10, 6) # Linspace divides line in given equal parts.

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [7]:
np.arange(0, 20, 2) # arange skips the given digits.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.random.randn(5,5)

array([[ 0.52607115, -0.99681913,  0.16701837, -1.13591767, -1.79663679],
       [-0.17787879, -0.52807663,  1.40357339, -0.65564339,  0.64486456],
       [-0.34477811, -0.13392212,  1.53558898, -0.57241048, -0.36395467],
       [-1.48477018,  1.58534586, -1.4346553 ,  0.12144731,  0.05020406],
       [-1.2071149 ,  0.03514818,  0.60788476, -0.77772809, -1.19963674]])

## Reshaping an array.

In [9]:
my_list = np.arange(0,20)
my_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
my_list.reshape(-4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 2D Arrays

In [11]:
my_2d_arraay = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
my_2d_arraay

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Grab 8 from 2,1
my_2d_arraay[2][1]

8

In [13]:
my_2d_arraay[:2,1:]

array([[2, 3],
       [5, 6]])

In [14]:
new_array = np.arange(0,30,2)

In [15]:
new_array[ new_array > 10 ]

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

## Basic operations

In [16]:
np.sqrt(new_array)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262])

In [17]:
np.mean(new_array)

14.0